// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKQuJcXDhChcsfZmHJT7EJ-UY2f_kQrC8',
    appId: '1:284813872429:web:b61f8c8784e71f7ddb57a4',
    messagingSenderId: '284813872429',
    projectId: 'bpklabmovel',
    authDomain: 'bpklabmovel.firebaseapp.com',
    storageBucket: 'bpklabmovel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMmee7ezuI-SXrCkEo5IzW4ki7hDkzNlc',
    appId: '1:284813872429:android:1e15f8bd0c8cec6fdb57a4',
    messagingSenderId: '284813872429',
    projectId: 'bpklabmovel',
    storageBucket: 'bpklabmovel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7wkh8O6Zzs3wz7yKEqBHcWWo8jM7cUNk',
    appId: '1:284813872429:ios:85f431115d280576db57a4',
    messagingSenderId: '284813872429',
    projectId: 'bpklabmovel',
    storageBucket: 'bpklabmovel.firebasestorage.app',
    iosBundleId: 'com.example.bpkLabmovel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7wkh8O6Zzs3wz7yKEqBHcWWo8jM7cUNk',
    appId: '1:284813872429:ios:85f431115d280576db57a4',
    messagingSenderId: '284813872429',
    projectId: 'bpklabmovel',
    storageBucket: 'bpklabmovel.firebasestorage.app',
    iosBundleId: 'com.example.bpkLabmovel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKQuJcXDhChcsfZmHJT7EJ-UY2f_kQrC8',
    appId: '1:284813872429:web:2bc665fa8e379da5db57a4',
    messagingSenderId: '284813872429',
    projectId: 'bpklabmovel',
    authDomain: 'bpklabmovel.firebaseapp.com',
    storageBucket: 'bpklabmovel.firebasestorage.app',
  );
}
